export const ALL_USER_REQUEST = 'ALL_USER_REQUEST';
export const ALL_USER_SUCCESS = 'ALL_USER_SUCCESS';
export const ALL_USER_FAILED = 'ALL_USER_FAILED';

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';

export const ADMIN_LOGOUT = 'ADMIN_LOGOUT';

export const CMS_DATA_REQUEST = ' CMS_DATA_REQUEST';
export const CMS_DATA_SUCCESS = ' CMS_DATA_SUCCESS';
export const CMS_DATA_FAILED = ' CMS_DATA_FAILED';

export const SUBADMIN_DATA_REQUEST = 'SUBADMIN_DATA_REQUEST ';
export const SUBADMIN_DATA_SUCCESS = 'SUBADMIN_DATA_SUCCESS';
export const SUBADMIN_DATA_FAILED = 'SUBADMIN_DATA_FAILED';

export const ADMIN_PROFILE_DATA_REQUEST = 'ADMIN_PROFILE_DATA_REQUEST ';
export const ADMIN_PROFILE_DATA_SUCCESS = 'ADMIN_PROFILE_DATA_SUCCESS';
export const ADMIN_PROFILE_DATA_FAILED = 'ADMIN_PROFILE_DATA_FAILED';
